# Generated by Django 3.1.5 on 2021-10-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sur', '0002_auto_20211007_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='backsong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
    ]
